### PR TITLE
Add 'to run (an application)', Add 'embedded system'

### PR DESCRIPTION
**Pull request by tahodzic**
Added the expressions for 
- to run (an application)
- Embedded system

### CODE REVIEW

**Comment by ronkorving** [comment]
Thanks for the contribution! I was only wondering about one detail. Would "embedded systems" not better fit under the `Devices` category? I may be wrong, I don't do any embedded development so don't have a particularly strong opinion one way or the other, and I'm not asking to change it unless you yourself think it would be good idea.

Can anyone else perhaps review the Japanese? Thanks :)

cc @AlmirKadric @Yuuki77

**Comment by tahodzic** [comment]
You're welcome! Great that there is such a list, I gladly contribute to it. 
My reasoning behind the chosen category is purely subjective: When I hear 'Embedded System' it's always connected to developing something, hence I put it under 'Software Development'. But of course I could be wrong.

**Comment by ronkorving** [comment]
Then let's leave it there, thanks 👍

**Comment by AlmirKadric** [comment]
@ronkorving 
Japanese looks fine, however we already have `実行` within the list
To run or execute an application or function under software development
Perhaps we can expand that explanation a bit? I personally don't mind the item appearing twice though

**Comment by ronkorving** [comment]
cc @tahodzic ^ :)

**Comment by tahodzic** [comment]
Interesting. I totally didn't see that. @AlmirKadric  sounds good, what do you have in mind? More usage examples?

**Comment by AlmirKadric** [comment]
@tahodzic if you didn't see it, potentially others won't either. So keeping it duplicated might be a valid solution. But I do think we should have consistency in the explanation. So perhaps extended usage explanation and then duplicate the item in 2 locations.

@ronkorving what do you think?

**Comment by ronkorving** [comment]
I would prefer to avoid duplication, but not a blocker. If @tahodzic would like to remove that one entry to avoid the duplication, I would be happiest. I'm afraid of the lists spiraling out of control if we allow duplicates :) Not that this repo receives 20 PRs per day, but still ;)

**Comment by AlmirKadric** [comment]
@ronkorving i do agree, its why i was thinking a JSON db with tagging and a rendering page would be a much better approach to this list (something I'm actually developing over here). Anyways, lets keep this clean and just make sure that item belongs in the correct group with proper usages and no duplication then.

@tahodzic 4649!

**Comment by tahodzic** [comment]
Ok, removed the redundant entry. お疲れさまでした！

**Comment by AlmirKadric** [comment]
LGTM 👍 
CC: @ronkorving

**Comment by ronkorving** [comment]
Thanks!

**Pull request merged**
