### PR TITLE
Adds links to jisho.org

### PR DESCRIPTION
**Pull request by beaucollins**
I found it handy to link directly to the jisho.org search results for each term.

### CODE REVIEW

**Comment by ronkorving** [comment]
Fantastic! :) This is going to make every other PR conflict, let me think about how I'm gonna do this...

**Comment by beaucollins** [comment]
If you keep merging in other PR's I'll keep fixing this one.

**Comment by ronkorving** [comment]
There is only 1 open PR (#4), and I will block all new incoming PRs until yours is merged. Yours is a great one that I would really love to see land, so I hope you can bear me with me here :) Once yours is in, I will update the Guideline section to require people to add these links.

**Comment by ronkorving** [comment]
(by the way, I'm not sure if that was intentional, but you closed your PR)

**Comment by beaucollins** [comment]
Wasn't intentional, I moved the branches around on my repo and it closed this one.

I'm rebasing against this master branch to add the other terms.

**Comment by ronkorving** [comment]
Awesome, thanks. Please also consider using a search URL instead of a word-URL, using the `#comp` tag (see #8). I wonder if that would give better output.

Any idea on when you will be able to do that? I'm blocking other PRs until that happens.

**Comment by ronkorving** [comment]
Alright, I'm gonna move forward with some other PRs until you can get back on this.

**Comment by beaucollins** [comment]
Yeah, don't wait for me. Sorry for the hold up.

**Pull request closed without merging**
