### PR TITLE
New word: Monitoring

### PR DESCRIPTION
**Pull request by stouf**
References:

- [Wikipedia page for "Network monitoring"](https://ja.wikipedia.org/wiki/%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF%E7%9B%A3%E8%A6%96)
- [Dictionary](http://jisho.org/word/%E7%9B%A3%E8%A6%96)

### CODE REVIEW

**Comment by j-holub** [comment]
I would change the formatting to `監視（する）` to match the rest of the vocabularies in the list.

**Comment by stouf** [comment]
@00SteinsGate00 

> I would change the formatting to 監視（する） to match the rest of the vocabularies in the list.

Good idea. Moreover, it's in the guidelines. I updated it, thanks for the suggestion.

**Comment by ronkorving** [comment]
Actually, the guidelines stipulates that in suru-verbs, you should write "To monitor" in this case ;)

**Comment by stouf** [comment]
In this case, it could be a noun as well as a verb (by appending する). I'm fine either way and I think people would understand it in both ways.
What do you guys prefer? I'll go for it.

**Comment by j-holub** [comment]
One could of course go about it and add it both. One row for `監視` and one for `監視する`.

But I'm just a guy watching this repo, not a maintainer, so my opinion should only be seen as an opinion. In the end it's up to @ronkorving to decide.

**Comment by ronkorving** [comment]
No, there's no need for both suru-form and non-suru form. Just stick with the suru-form please. The braces around する are supposed to indicate that it can be used as a noun too.

**Comment by stouf** [comment]
> Just stick with the suru-form please.

Done Sir!

**Comment by ronkorving** [comment]
Thanks :)

**Pull request merged**
